name: sample_environment
channels:
  - bioconda
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - anndata=0.7.4
  - cellrank-krylov=1.0.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - ipykernel
  - mpi=1.0
  - mpi4py=3.0.3
  - networkx=2.5
  - numpy=1.19.2
  - pandas=1.1.4
  - petsc=3.14.0
  - petsc4py=3.14.0
  - pygam=0.8.0
  - python=3.8.6
  - scanpy=1.6.0
  - scikit-learn=0.23.2
  - scipy=1.5.3
  - scvelo=0.2.2
  - seaborn=0.11.0
  - slepc=3.14.0
  - slepc4py=3.14.0
  - statsmodels=0.12.1
  - umap-learn=0.4.6
